<a href="https://colab.research.google.com/github/satvikakarumudi/PyTorch-Files/blob/main/00Exercises_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.rand(7,7)

tensor([[0.3426, 0.9262, 0.9524, 0.7958, 0.2387, 0.0091, 0.3082],
        [0.2430, 0.3665, 0.8024, 0.8570, 0.1140, 0.8363, 0.0594],
        [0.5927, 0.9244, 0.8189, 0.5384, 0.2868, 0.0973, 0.9470],
        [0.4599, 0.8519, 0.9869, 0.6912, 0.0336, 0.8480, 0.5851],
        [0.1113, 0.9797, 0.2001, 0.6603, 0.0502, 0.8842, 0.1744],
        [0.9012, 0.2758, 0.7212, 0.4953, 0.9264, 0.1533, 0.8792],
        [0.1512, 0.2096, 0.1372, 0.6712, 0.2460, 0.8350, 0.0312]])

In [2]:
torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[1.4233],
        [2.5205],
        [1.7060],
        [1.6688],
        [2.5774],
        [1.9618],
        [1.4954]])

In [3]:
random_seed=0
torch.manual_seed(random_seed)
print(torch.rand(7,7))

torch.manual_seed(random_seed)
torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])