<a href="https://colab.research.google.com/github/satvikakarumudi/PyTorch-Files/blob/main/00Sat_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


##Introduction to Tensors
### Creating Tensors

In [ ]:
#SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#VECTOR
vector=torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX=torch.tensor([[1,2,3],
                     [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR=torch.tensor([[[1,2],
                      [3,4],
                      [5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 2])

In [ ]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
TENSOR=torch.tensor([[[1,2],
                      [2,5],
                      [3,6],
                      [4,5],
                      [5,9]]])
TENSOR

tensor([[[1, 2],
         [2, 5],
         [3, 6],
         [4, 5],
         [5, 9]]])

In [ ]:
TENSOR.shape

torch.Size([1, 5, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [2, 5],
        [3, 6],
        [4, 5],
        [5, 9]])

In [ ]:
TENSOR=torch.tensor([[[1],
                      [2],
                      [3],
                      [4]]])
TENSOR

tensor([[[1],
         [2],
         [3],
         [4]]])

In [ ]:
TENSOR.shape

torch.Size([1, 4, 1])

In [ ]:
TENSOR[0]

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
TENSOR=torch.Tensor([[[1.1,2.2,3.3,4.4],
                      [5.5,6.6,7.7,8.8]]])
TENSOR

tensor([[[1.1000, 2.2000, 3.3000, 4.4000],
         [5.5000, 6.6000, 7.7000, 8.8000]]])

In [ ]:
TENSOR.shape

torch.Size([1, 2, 4])

In [ ]:
MATRIX=torch.tensor([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]])
MATRIX

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
MATRIX[1]

tensor([5, 6, 7, 8])

In [ ]:
MATRIX[0]

tensor([1, 2, 3, 4])

In [ ]:
MATRIX[2]

tensor([ 9, 10, 11, 12])

In [ ]:
MATRIX.ndim

2

##RANDOM TENSORS

In [ ]:
#CREATE A RANDOM TENSOR OF SIZE (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5275, 0.1994, 0.6962, 0.4351],
        [0.8833, 0.5145, 0.4455, 0.3097],
        [0.3772, 0.9203, 0.5331, 0.8897]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor=torch.rand(10,10)
random_tensor



tensor([[0.8693, 0.2242, 0.8227, 0.9871, 0.6957, 0.7726, 0.1721, 0.3821, 0.1408,
         0.7868],
        [0.2225, 0.9798, 0.5587, 0.2484, 0.9899, 0.2503, 0.1422, 0.0836, 0.1245,
         0.6260],
        [0.9858, 0.5290, 0.6794, 0.7002, 0.4335, 0.4836, 0.0709, 0.0138, 0.2330,
         0.3713],
        [0.4213, 0.9418, 0.4703, 0.3955, 0.7921, 0.4084, 0.8066, 0.0992, 0.5396,
         0.6750],
        [0.6806, 0.9028, 0.9473, 0.3392, 0.4466, 0.2943, 0.3822, 0.5553, 0.3889,
         0.3521],
        [0.7045, 0.9692, 0.2066, 0.7094, 0.4421, 0.0421, 0.0373, 0.5567, 0.9784,
         0.2663],
        [0.9282, 0.0198, 0.7148, 0.1526, 0.2937, 0.9418, 0.2471, 0.7278, 0.6950,
         0.9751],
        [0.3161, 0.7066, 0.2490, 0.8777, 0.0229, 0.2703, 0.2678, 0.5148, 0.0033,
         0.4484],
        [0.0516, 0.5392, 0.7141, 0.7098, 0.4346, 0.1830, 0.1935, 0.3200, 0.5831,
         0.5412],
        [0.4863, 0.0655, 0.5003, 0.7682, 0.9640, 0.7698, 0.7686, 0.5435, 0.8630,
         0.9763]])

In [ ]:
random_tensor.ndim

2

In [ ]:
10*10*10

1000

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4283, 0.6257, 0.9942, 0.4556],
        [0.0180, 0.6644, 0.2273, 0.4406],
        [0.3704, 0.2616, 0.3438, 0.1423]])

In [ ]:
##create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,colour(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(2,2)

tensor([[0.2715, 0.0693],
        [0.0624, 0.2049]])