<a href="https://colab.research.google.com/github/satvikakarumudi/PyTorch-Files/blob/main/01Sat_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Zeroes and Ones**

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
#create a tensor of all zeros
zeros=torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
random_tensor=torch.rand(3,4)
random_tensor



tensor([[0.7942, 0.5848, 0.6911, 0.6709],
        [0.2263, 0.1317, 0.2119, 0.7560],
        [0.7080, 0.3221, 0.4330, 0.2449]])

In [10]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
#create a tensor of all ones
ones=torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
ones.dtype

torch.float32

In [15]:
random_tensor.dtype

torch.float32

In [16]:
#Examples
zeros=torch.zeros((1,1))
zeros

tensor([[0.]])

In [17]:
zeros=torch.zeros((5,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [18]:
ones=torch.ones((5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

###CREATING OF RANGE OF TENSORS AND TENSORS-LIKE




In [19]:
#use torch.range()
torch.range(0,10)

<ipython-input-19-d32bca609d4d>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
torch.range(0,4)

<ipython-input-20-520d0ef524fa>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,4)


tensor([0., 1., 2., 3., 4.])

In [21]:
torch.range(2,5)

<ipython-input-21-380d79b9a7e8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2,5)


tensor([2., 3., 4., 5.])

In [22]:
torch.__version__

'2.1.0+cu121'

In [23]:
#use arange
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
one_to_ten=torch.arange(1,9)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
one_to_ten=torch.arange(start=0,end=100,step=4)
one_to_ten

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])

In [27]:
one_to_forty=torch.arange(start=0,end=40,step=1)
one_to_forty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39])

In [28]:
#creating tensors like
one_to_ten

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])

In [31]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

In [32]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

In [34]:
one_to_five=torch.arange(1,5)
one_to_five

tensor([1, 2, 3, 4])

In [35]:
one_to_five=torch.arange(start=1,end=5,step=2)
one_to_five

tensor([1, 3])

In [36]:
five_ones=torch.ones_like(input=one_to_five)
five_ones

tensor([1, 1])

**TENSOR DATATYPES**

Tensor datatypes is one of the 3 big errors you'll into with PyTorch and Deep learning
1.Tensors not right datatype

2.Tensors not shape

3.Tensors not on the right device

In [37]:
## Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None )
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [45]:
float_32_tensor*int_32_tensor

tensor([ 3., 12., 27.])

In [48]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.long)
int_32_tensor

tensor([1, 2, 3])

In [49]:
float_32_tensor*int_32_tensor

tensor([ 3., 12., 27.])

###Getting information from tensors(tensor atttributes)

1.Tensors not right datatype:to do get datatypes from a tensor, can use 'tensor.dtype'

2.Tensors not shape:to get shape from a tensor , can use 'tensor.shape'

3.Tensors not on the right device:to get device from a tensor,can use 'tensor.device'

In [50]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1075, 0.8454, 0.6534, 0.9868],
        [0.0213, 0.1237, 0.6983, 0.2634],
        [0.2555, 0.1119, 0.9853, 0.2453]])

In [51]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [53]:
some_tensor.size()

torch.Size([3, 4])

In [55]:
## Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.1075, 0.8454, 0.6534, 0.9868],
        [0.0213, 0.1237, 0.6983, 0.2634],
        [0.2555, 0.1119, 0.9853, 0.2453]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu
