<a href="https://colab.research.google.com/github/satvikakarumudi/PyTorch-Files/blob/main/02Sat_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Manipulating Tensors (Tensor Operations)**

Tensor operations include:

Addistion

Subtraction

Multiplication

Division

Matrix Multiplication

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
## Create a tensor
## Addition of tensor

tensor=torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [3]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [4]:
## Multiplication of tensor

tensor*4

tensor([ 4,  8, 12])

In [5]:
tensor

tensor([1, 2, 3])

In [6]:
## Subtraction of tensor

tensor-2

tensor([-1,  0,  1])

In [7]:
## Divison of tensor

tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [8]:
tensor=torch.tensor([50,60,70])

In [9]:
tensor+1

tensor([51, 61, 71])

In [10]:
tensor-1

tensor([49, 59, 69])

In [11]:
tensor*2

tensor([100, 120, 140])

In [12]:
tensor/5

tensor([10., 12., 14.])

**Performing operations using PyTorch in-built functions**

In [13]:
tensor=torch.tensor([10,20,30])

In [14]:
torch.mul(tensor,6)

tensor([ 60, 120, 180])

In [15]:
torch.add(tensor,5)

tensor([15, 25, 35])

In [16]:
torch.div(tensor,5)

tensor([2., 4., 6.])

In [17]:
torch.sub(tensor,3)

tensor([ 7, 17, 27])

##**Matrix Multiplication**

Two main ways of performing mutiplication in neural networks and deep learning

1.Elements-wise multiplication

2.Matrix Multiplication(dot product)

In [18]:
## Elememt-wise multiplication

print(tensor*tensor)

tensor([100, 400, 900])


In [20]:
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")


tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals:tensor([100, 400, 900])


In [21]:
## Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(1400)

In [22]:
## Matrix multiplication by hand

1*1+2*2+3*3

14

In [25]:
tensor@tensor

tensor(1400)

In [23]:
%%time

value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
  print(value)

tensor(100)
tensor(500)
tensor(1400)
CPU times: user 3.64 ms, sys: 831 µs, total: 4.47 ms
Wall time: 4.44 ms


In [24]:
%%time

torch.matmul(tensor,tensor)

CPU times: user 1.13 ms, sys: 6 µs, total: 1.13 ms
Wall time: 1.14 ms


tensor(1400)

Rules for matrix multiplication:

1.The **inner dimensions**
*  (3,2)@(3,2)` won't work

*  (2,3)@(3,2) will work

*  (3,2)@(2,3) will work

2.The resulting matrix has the shape of **outer dimensions**
*  (2,3)@(3,2)->(2,2)

*  (3,2)@(2,3)->(3,3)

In [26]:
torch.rand(3,2)

tensor([[0.3951, 0.0312],
        [0.5358, 0.8462],
        [0.0999, 0.5844]])

In [27]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [28]:
## Won't work (inner dimensions)

torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [29]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4807, 0.2466, 0.4314],
        [0.4721, 0.2071, 0.5978],
        [0.9838, 0.5187, 0.8136]])

In [30]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1232, 0.3035, 0.1432],
        [0.1343, 0.7468, 0.4302],
        [0.2506, 0.4889, 0.2067]])

In [32]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[3.7809, 3.3134, 3.3921],
        [3.6148, 2.8521, 2.6098],
        [3.1350, 2.7671, 2.2409]])

In [33]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.8710, 3.5932, 3.4131, 3.3205, 2.1899, 2.2609, 3.1934, 2.0838, 3.1136,
         3.0049],
        [3.2594, 3.4867, 3.7151, 3.4868, 1.8155, 2.3510, 3.4005, 1.6954, 2.9001,
         2.4325],
        [3.2834, 3.5703, 3.4726, 3.0760, 1.6214, 2.3500, 3.0317, 1.6265, 2.7281,
         2.1235],
        [3.3921, 4.3652, 3.5565, 3.5415, 1.9016, 2.4374, 3.9152, 2.2208, 2.9999,
         2.5841],
        [2.3573, 2.8515, 2.6859, 2.2321, 1.7914, 1.6146, 2.4579, 1.8174, 2.2565,
         2.6657],
        [2.9567, 2.4971, 3.2078, 2.7185, 1.1264, 1.9487, 2.1958, 0.9978, 2.4349,
         2.0297],
        [2.8350, 2.6440, 2.9706, 2.2223, 0.9767, 1.7068, 2.3423, 1.1581, 2.3256,
         1.8315],
        [2.7401, 3.3978, 3.2214, 3.0811, 2.2981, 2.2228, 3.1012, 1.9937, 2.7621,
         2.5000],
        [2.1754, 2.4465, 2.0617, 2.3231, 1.4035, 1.5407, 2.2365, 1.5473, 1.6247,
         1.7693],
        [2.3027, 3.1225, 2.7297, 2.5622, 1.6066, 2.0990, 2.8726, 1.6022, 2.6618,
         1.4035]])

One of the most common errors in deep learning : **SHAPE ERRORS**

In [35]:
## Shapes for matrix multiplication

tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [36]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix our tensor shape issues ,we can manipulatethe shape of one of our tensors using a **Transpose**

 A **Transpose** switches the axes or dimensions of a given tensor

In [39]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [43]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [42]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [48]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [50]:
## The matrix multiplication works when tensor_B is transpose


print(f"Original shapes:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape}(same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape}@{tensor_B.T.shape}<-inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shapes:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2])(same shape as above),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2])@torch.Size([2, 3])<-inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


In [52]:
##EXAMPLE##

tensor_C=torch.tensor([[1,2,3],
                       [10,20,30]])
tensor_D=torch.tensor([[4,5,6],
                       [40,50,60]])

In [53]:
tensor_C.shape

torch.Size([2, 3])

In [54]:
tensor_D.shape

torch.Size([2, 3])

In [55]:
tensor_C.T

tensor([[ 1, 10],
        [ 2, 20],
        [ 3, 30]])

In [56]:
tensor_C.T.shape

torch.Size([3, 2])

In [57]:
torch.matmul(tensor_C.T,tensor_D)

tensor([[ 404,  505,  606],
        [ 808, 1010, 1212],
        [1212, 1515, 1818]])

In [58]:
torch.matmul(tensor_C.T,tensor_D).shape

torch.Size([3, 3])

**Finding the min,max,mean,sum,etc(tensor aggregation)**

In [78]:
##Create a tensor

x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [79]:
## Find the min

torch.min(x),x.min()

(tensor(0), tensor(0))

In [82]:
## Find the max

torch.max(x),x.max()

(tensor(90), tensor(90))

In [81]:
## Find the mean()-Requires a tensorof float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [83]:
x.type(torch.float32).mean()

tensor(45.)

In [84]:
## Find the sum

torch.sum(x),x.sum()

(tensor(450), tensor(450))

**Finding the positional min and max**

In [85]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
## Finding the position in tensor that has the minimum value with argmin()->return index position of target tensor where the minimum value occurs

x.argmin()

tensor(0)

In [87]:
x[0]

tensor(0)

In [88]:
## Finding the position in tensor that has the maximum value with argmax()->return index position of target tensor where the maximum value occurs

x.argmax()

tensor(9)

In [89]:
x[9]

tensor(90)

In [90]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])