<a href="https://colab.research.google.com/github/satvikakarumudi/PyTorch-Files/blob/main/03Sat_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Reshaping,stacking,squeezing and unsqueezing tensors**

1.Reshaping-reshapes an input tensor to a defined shape

2.View-Return a view of an input tensor of certain shape but keep the same memory as the original tensor

3.Stacking-Combine multiple tensors on top each other (vstack) or side by side(hstack)

4.Squeeze-removes all 1 dimension from a tensor

5.Unsqueeze-add 1 dimension to target tensor

6.Permute-Return a view of the input with dimensions permuted(swapped)ina certain way

In [16]:
#Let's create a tesnor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [13]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [19]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [20]:
#changing z changes x(because the view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [21]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [22]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [27]:
#torch.sqeeze()-removes all single dimensions from a target tensor
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")


Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape:torch.Size([1, 9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [31]:
#torch.unsqueezes()-adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

x_reshaped.shape

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:torch.Size([9, 1])


torch.Size([1, 9])

In [32]:
#torch.unsqueezes()-adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

x_reshaped.shape

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


torch.Size([1, 9])

In [36]:
#torch.permute-rearrange the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))

#permute the original tensor to rearrange the axis order
x_permuted=x_original.permute(2,0,1)#shifts axis 0->1, 1->2, 2->0
print(f"previous shape:{x_original.shape}")
print(f"New shape: {x_permuted.shape}")


previous shape:torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [26]:
x_reshaped.squeeze().shape

torch.Size([9])

In [38]:
x_original[0,0,0]

tensor(0.6032)

In [39]:
x_original[:,:,0]

tensor([[0.6032, 0.2666, 0.1875,  ..., 0.6296, 0.2720, 0.7633],
        [0.4663, 0.8104, 0.6644,  ..., 0.0134, 0.3448, 0.6281],
        [0.0842, 0.1128, 0.5860,  ..., 0.6172, 0.5466, 0.0831],
        ...,
        [0.6040, 0.3089, 0.7983,  ..., 0.8735, 0.2377, 0.1757],
        [0.1872, 0.0243, 0.3430,  ..., 0.0850, 0.8620, 0.4413],
        [0.8950, 0.0625, 0.0642,  ..., 0.6388, 0.1947, 0.8380]])

In [40]:
x_original[0,:,:]

tensor([[0.6032, 0.5697, 0.6439],
        [0.2666, 0.5861, 0.1254],
        [0.1875, 0.7796, 0.3333],
        [0.6848, 0.4121, 0.6201],
        [0.6417, 0.1197, 0.9526],
        [0.7925, 0.7569, 0.7542],
        [0.4119, 0.1852, 0.5481],
        [0.4326, 0.9440, 0.0139],
        [0.5594, 0.7195, 0.6246],
        [0.3981, 0.2878, 0.8596],
        [0.6242, 0.6216, 0.2645],
        [0.7274, 0.4979, 0.0564],
        [0.0715, 0.1827, 0.7558],
        [0.0121, 0.4707, 0.2057],
        [0.3904, 0.7739, 0.7751],
        [0.5826, 0.8842, 0.2822],
        [0.8995, 0.0180, 0.6064],
        [0.9326, 0.9377, 0.6233],
        [0.0061, 0.5166, 0.3323],
        [0.7209, 0.9881, 0.9869],
        [0.3655, 0.0584, 0.5452],
        [0.8928, 0.0296, 0.4913],
        [0.7159, 0.8030, 0.7343],
        [0.8226, 0.1755, 0.9996],
        [0.1451, 0.2894, 0.7991],
        [0.1965, 0.8642, 0.5843],
        [0.5243, 0.8930, 0.8216],
        [0.3227, 0.6400, 0.5506],
        [0.2241, 0.3124, 0.3440],
        [0.629

In [41]:
x_original[0,0,0]=72818
x_original[0,0,0],x_permuted[0,0,0]

(tensor(72818.), tensor(72818.))

**Indexing(selecting data from tensors)**

Indexing with PyTorch is similar to indexing with NumPy

In [60]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
#Lets index on middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [57]:
#Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [56]:
x[0][0][1]

tensor(2)

In [55]:
x[0][1][1]

tensor(5)

In [61]:
#You can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [64]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [65]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions
x[:,1,1]

tensor([5])

In [67]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [68]:
#Index on x to return 9
print(x[0][2][2])

#Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


In [69]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

**PyTorch tensors and NumPy**

NumPy is a popular scientific python numerical computing library.
And because of this,PyTorch has functionality to interact with it.

1.Data in NumPy, want in PyTorch tensor->torch.from_numpy(ndarray)

2.PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [78]:
#NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [84]:
#Change the value of array, what will this do to 'tensor'?
array=array+1
array, tensor, array.dtype


(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'))

In [86]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
numpy_tensor.dtype

dtype('float32')

In [81]:
torch.arange(1.0,8.0).dtype

torch.float32

In [88]:
#Change the tensor what happens to numpy_tensor?
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducability(trying to take random out of random)**

In short how a neural networks learns:

Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again....


To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.Essentially what the random seed does is "flavour" the randomness.

In [90]:
torch.rand(3,3)

tensor([[0.1024, 0.4665, 0.1926],
        [0.6667, 0.4364, 0.5258],
        [0.2794, 0.2761, 0.1402]])

In [91]:
#Create two random tensors

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)



tensor([[0.7234, 0.7845, 0.3862, 0.8003],
        [0.3659, 0.4476, 0.5819, 0.5975],
        [0.2044, 0.5169, 0.5366, 0.8120]])
tensor([[0.9535, 0.6984, 0.7200, 0.6757],
        [0.8224, 0.4853, 0.1298, 0.1895],
        [0.8507, 0.6702, 0.4818, 0.2634]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [92]:
1==1

True

In [95]:
#Lets make some random but reproducible tensors

#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running tensors and PyTorch objects on the GPUs**

**GETTING A GPU**

1.Easiest-Use Google Colab for a free GPU

2.Use your own GPU

3.Use cloud computing

In [1]:
!nvidia-smi

Mon Feb 12 11:46:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

**CHECK FOR GPU ACCESS WITH PYTORCH**

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#Count number of devices
torch.cuda.device_count()

1

**PUTTING TENSORS AND MODELS ON THE GPU**

In [5]:
#Create a tensor (default on the CPU)
import torch
tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
#Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**MOVING TENSORS BACK TO THE CPU**

In [8]:
#If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
#to fix the GPU tensor with NumPy issue , we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')